import React, { useEffect, useState, useMemo } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useMeetingRequest, useMeetingMasters } from '../features/meetings/hooks';
import { createMeetingRequest, updateMeetingRequest } from '../features/meetings/meetingService';
import { useRequestShortlists } from '../features/venues/hooks';
import { ROUTES } from '../routes/routeRegistry';
import { ROLES } from '../auth/permissions';
import { Search, AlertCircle, FileText, MapPin, Utensils, Settings } from 'lucide-react';
import { ParticipantMixGrid } from '../components/ParticipantMixGrid';
import { MultiSelectCheckbox, RadioGroup, FormSection, MultiSelectDropdown } from '../components/FormControls';
import { createEmptyParticipantMix, calculateTotalPlannedPax, validateGuaranteedPax } from '../features/rooms/roomCalculator';
import type { ParticipantMix } from '../features/rooms/types';
import { ZONE_OPTIONS } from '../constants/zones';
import {
  SEATING_STYLES,
  AV_REQUIREMENTS,
  FOOD_REQUIREMENTS,
  TRANSFER_OPTIONS,
  PREFERRED_LOCALITIES,
  MAX_PREFERRED_HOTELS,
  formatMultiSelectValue,
  parseMultiSelectValue,
  generateMeetingName,
} from '../constants/formOptions';

function Panel({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ padding: 16, border: '1px solid var(--border)', borderRadius: 8, background: 'var(--surface)' }}>
      {children}
    </div>
  );
}

const initialFormState = {
  meeting_name: '',
  division_id: '',
  meeting_type_id: '',
  city_id: '',
  zone: '',
  start_date: '',
  end_date: '',
  expected_pax: 0,
  guaranteed_pax: 0,
  residential_flag: false,
  rooms_required: 0,
  halls_required: 0,
  seating_style: '',
  av_requirements: '',
  food_requirements: '',
  transfer_requirements: 'NOT_REQUIRED',
  // Participant Mix fields
  participant_so: 0,
  participant_dm: 0,
  participant_rsm: 0,
  participant_ch: 0,
  participant_ibh: 0,
  participant_others: 0,
  // Step 5: Venue Preferences (Optional)
  preferred_hotels: '',
  preferred_locality: '',
  venue_preference_notes: '',
  additional_notes: '',
};

// Step 5: Multi-select state interfaces
interface FormMultiSelectState {
  seatingStyles: string[];
  avRequirements: string[];
  foodRequirements: string[];
  preferredHotels: string[];
}

export function MeetingRequestForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();

  const { request, loading: requestLoading, refresh } = useMeetingRequest(id as string | undefined);
  const { shortlists } = useRequestShortlists(request?.id ?? null);
  const { divisions, cities, meetingTypes, loading: mastersLoading, error: mastersError } = useMeetingMasters();

  const [form, setForm] = useState<typeof initialFormState>(initialFormState);
  const [participantMix, setParticipantMix] = useState<ParticipantMix>(createEmptyParticipantMix());
  const [multiSelect, setMultiSelect] = useState<FormMultiSelectState>({
    seatingStyles: [],
    avRequirements: [],
    foodRequirements: [],
    preferredHotels: [],
  });
  const [guaranteedPaxError, setGuaranteedPaxError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGeneratedName, setAutoGeneratedName] = useState(false);

  const isAdmin = !!(user && (user.role === ROLES.ADMIN || user.role === ROLES.SUPER_ADMIN));
  const canEdit = !isAdmin && (!request || request.status === 'DRAFT');

  // Calculate total planned pax from participant mix
  const totalPlannedPax = calculateTotalPlannedPax(participantMix);

  // Filter cities by zone
  const filteredCities = useMemo(() => {
    if (!form.zone) return cities;
    // For now, return all cities. Zone filtering logic from Step 3 already in place
    return cities;
  }, [cities, form.zone]);

  useEffect(() => {
    if (!request) {
      setForm((current) => ({
        ...current,
        division_id: user?.division_id ?? current.division_id,
      }));
      setParticipantMix(createEmptyParticipantMix());
      setMultiSelect({
        seatingStyles: [],
        avRequirements: [],
        foodRequirements: [],
        preferredHotels: [],
      });
      return;
    }

    setForm({
      meeting_name: request.meeting_name || '',
      division_id: request.division_id || user?.division_id || '',
      meeting_type_id: request.meeting_type_id || '',
      city_id: request.city_id || '',
      zone: request.zone || '',
      start_date: request.start_date || '',
      end_date: request.end_date || '',
      expected_pax: request.expected_pax ?? 0,
      guaranteed_pax: request.guaranteed_pax ?? 0,
      residential_flag: !!request.residential_flag,
      rooms_required: request.rooms_required ?? 0,
      halls_required: request.halls_required ?? 0,
      seating_style: request.seating_style || '',
      av_requirements: request.av_requirements || '',
      food_requirements: request.food_requirements || '',
      transfer_requirements: request.transfer_requirements || 'NOT_REQUIRED',
      // Load participant mix from request
      participant_so: request.participant_so ?? 0,
      participant_dm: request.participant_dm ?? 0,
      participant_rsm: request.participant_rsm ?? 0,
      participant_ch: request.participant_ch ?? 0,
      participant_ibh: request.participant_ibh ?? 0,
      participant_others: request.participant_others ?? 0,
      // Load venue preferences
      preferred_hotels: request.preferred_hotels || '',
      preferred_locality: request.preferred_locality || '',
      venue_preference_notes: request.venue_preference_notes || '',
      additional_notes: request.additional_notes || '',
    });
    
    // Set participant mix state
    setParticipantMix({
      so: request.participant_so ?? 0,
      dm: request.participant_dm ?? 0,
      rsm: request.participant_rsm ?? 0,
      ch: request.participant_ch ?? 0,
      ibh: request.participant_ibh ?? 0,
      others: request.participant_others ?? 0,
    });

    // Parse multi-select fields
    setMultiSelect({
      seatingStyles: parseMultiSelectValue(request.seating_style || ''),
      avRequirements: parseMultiSelectValue(request.av_requirements || ''),
      foodRequirements: parseMultiSelectValue(request.food_requirements || ''),
      preferredHotels: parseMultiSelectValue(request.preferred_hotels || ''),
    });
  }, [request, user?.division_id]);

  // Auto-generate meeting name when key fields change
  useEffect(() => {
    if (!canEdit || !autoGeneratedName) return;

    const division = divisions.find(d => d.id === form.division_id);
    const meetingType = meetingTypes.find(mt => mt.id === form.meeting_type_id);
    const city = cities.find(c => c.id === form.city_id);

    if (division && meetingType && city && form.start_date) {
      const generatedName = generateMeetingName(
        division.division_name,
        meetingType.meeting_type_name,
        city.city_name,
        form.start_date
      );
      if (generatedName) {
        setForm(prev => ({ ...prev, meeting_name: generatedName }));
      }
    }
  }, [form.division_id, form.meeting_type_id, form.city_id, form.start_date, autoGeneratedName, canEdit, divisions, meetingTypes, cities]);

  const handleChange = (field: keyof typeof initialFormState, value: string | number | boolean) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    
    // Clear guaranteed pax error when user changes the value
    if (field === 'guaranteed_pax') {
      setGuaranteedPaxError(null);
    }

    // If user manually edits meeting name, disable auto-generation
    if (field === 'meeting_name') {
      setAutoGeneratedName(false);
    }
  };

  const handleGenerateMeetingName = () => {
    setAutoGeneratedName(true);
    const division = divisions.find(d => d.id === form.division_id);
    const meetingType = meetingTypes.find(mt => mt.id === form.meeting_type_id);
    const city = cities.find(c => c.id === form.city_id);

    if (division && meetingType && city && form.start_date) {
      const generatedName = generateMeetingName(
        division.division_name,
        meetingType.meeting_type_name,
        city.city_name,
        form.start_date
      );
      if (generatedName) {
        setForm(prev => ({ ...prev, meeting_name: generatedName }));
      }
    }
  };

  const handleParticipantMixChange = (mix: ParticipantMix) => {
    setParticipantMix(mix);
    // Update form state with participant mix values
    setForm((prev) => ({
      ...prev,
      participant_so: mix.so,
      participant_dm: mix.dm,
      participant_rsm: mix.rsm,
      participant_ch: mix.ch,
      participant_ibh: mix.ibh,
      participant_others: mix.others,
    }));
  };

  const handleMultiSelectChange = (field: keyof FormMultiSelectState, values: string[]) => {
    setMultiSelect(prev => ({ ...prev, [field]: values }));
    
    // Update form state with formatted comma-separated string
    const formattedValue = formatMultiSelectValue(values);
    
    if (field === 'seatingStyles') {
      setForm(prev => ({ ...prev, seating_style: formattedValue }));
    } else if (field === 'avRequirements') {
      setForm(prev => ({ ...prev, av_requirements: formattedValue }));
    } else if (field === 'foodRequirements') {
      setForm(prev => ({ ...prev, food_requirements: formattedValue }));
    } else if (field === 'preferredHotels') {
      setForm(prev => ({ ...prev, preferred_hotels: formattedValue }));
    }
  };

  const validateForm = (): boolean => {
    // Validate end date
    if (form.start_date && form.end_date && form.end_date < form.start_date) {
      setError('End date cannot be earlier than start date');
      return false;
    }

    // Validate guaranteed pax
    const validation = validateGuaranteedPax(form.guaranteed_pax, totalPlannedPax);
    if (!validation.valid) {
      setGuaranteedPaxError(validation.error || null);
      return false;
    }
    
    // Check if participant mix is provided
    if (totalPlannedPax === 0) {
      setError('At least one participant is required');
      return false;
    }
    
    setGuaranteedPaxError(null);
    setError(null);
    return true;
  };

  const handleSaveDraft = async () => {
    if (!validateForm()) {
      return;
    }
    
    setSaving(true);
    setError(null);
    try {
      if (request) {
        await updateMeetingRequest(request.id, { ...form });
        await refresh?.();
        alert('Draft saved successfully.');
      } else if (user) {
        const created = await createMeetingRequest({ ...form }, user);
        navigate(ROUTES.meetingRequestView.replace(':id', created.id));
      }
    } catch (err: any) {
      setError(err.message || 'Failed to save draft');
    } finally {
      setSaving(false);
    }
  };

  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }
    
    setSaving(true);
    setError(null);
    try {
      if (request) {
        await updateMeetingRequest(request.id, { ...form }, 'SUBMITTED_TO_ADMIN');
        await refresh?.();
      } else if (user) {
        const created = await createMeetingRequest({ ...form }, user, 'SUBMITTED_TO_ADMIN');
        navigate(ROUTES.meetingRequestView.replace(':id', created.id));
      }
      alert('Request submitted to Admin.');
    } catch (err: any) {
      setError(err.message || 'Failed to submit request');
    } finally {
      setSaving(false);
    }
  };

  if (requestLoading || mastersLoading) return <div style={{ padding: 24 }}>Loading request form…</div>;
  if (mastersError) return <div style={{ padding: 24, color: 'red' }}>Failed to load form options: {mastersError}</div>;

  return (
    <div style={{ maxWidth: 980, margin: '0 auto', padding: 20, display: 'grid', gap: 16 }}>
      <h2 style={{ margin: 0 }}>{request ? `Request ${request.request_number}` : 'New Request'}</h2>

      {isAdmin ? (
        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 12 }}>
          <Panel>
            <h3 style={{ marginTop: 0 }}>Request Summary</h3>
            <div><strong>Meeting:</strong> {request?.meeting_name ?? '—'}</div>
            <div><strong>Division:</strong> {request?.divisions?.division_name ?? '—'}</div>
            <div><strong>Type:</strong> {request?.meeting_types?.meeting_type_name ?? '—'}</div>
            <div><strong>City:</strong> {request?.cities?.city_name ?? request?.target_city_name ?? '—'}</div>
            <div><strong>Zone:</strong> {request?.zone ?? '—'}</div>
            <div><strong>Dates:</strong> {request?.start_date ?? '—'} — {request?.end_date ?? '—'}</div>
            <div><strong>Pax:</strong> {request?.expected_pax ?? 0} expected / {request?.guaranteed_pax ?? 0} guaranteed</div>
            <div><strong>Accommodation Required:</strong> {request?.residential_flag ? 'Yes' : 'No'}</div>
            <div><strong>Rooms Required:</strong> {request?.rooms_required ?? 0}</div>
            <div><strong>Halls Required:</strong> {request?.halls_required ?? 0}</div>
            <div><strong>Seating Style:</strong> {request?.seating_style || '—'}</div>
            <div><strong>AV Requirements:</strong> {request?.av_requirements || '—'}</div>
            <div><strong>Food Requirements:</strong> {request?.food_requirements || '—'}</div>
            <div><strong>Transport Requirements:</strong> {request?.transfer_requirements || '—'}</div>
            <hr />
            <h4>Sales Head Recommendations</h4>
            {shortlists && shortlists.length > 0 ? (
              <ul>
                {shortlists.map((s) => (
                  <li key={s.id} style={{ marginBottom: 8, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>{s.hotels?.hotel_name ?? s.hotel_id}</span>
                    <div style={{ display: 'flex', gap: 8 }}>
                      <button onClick={() => navigate(`${ROUTES.venueDetails}?id=${s.hotel_id}`)} className="btn btn-secondary">View</button>
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <div style={{ color: 'var(--text-muted)' }}>No recommendations submitted.</div>
            )}
          </Panel>

          <Panel>
            <h3 style={{ marginTop: 0 }}>Admin Actions</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <button className="btn btn-primary" onClick={async () => {
                if (!request) return;
                await updateMeetingRequest(request.id, {}, 'AVAILABILITY_CHECK');
                refresh?.();
                alert('Availability check started');
              }}>
                Check Availability
              </button>
              <button className="btn btn-secondary" onClick={() => navigate(`${ROUTES.venueExplorer}?requestId=${id}`)}>
                Find Matching Venues
              </button>
              <button className="btn btn-primary" onClick={() => navigate(`${ROUTES.bookingNew}?requestId=${id}`)}>
                Create Booking
              </button>
            </div>
          </Panel>
        </div>
      ) : (
        <div style={{ display: 'grid', gap: 16 }}>
          <Panel>
            <h3 style={{ marginTop: 0 }}>Editable Request Form</h3>
            {request && request.status !== 'DRAFT' && (
              <div style={{ marginBottom: 12, color: 'var(--text-muted)' }}>
                This request has been submitted and is now read-only.
              </div>
            )}
            <div style={{ display: 'grid', gap: 16 }}>
              <div style={{ display: 'grid', gap: 12 }}>
                <label style={{ display: 'block', fontWeight: 600 }}>Meeting Name</label>
                <input
                  value={form.meeting_name}
                  onChange={(e) => handleChange('meeting_name', e.target.value)}
                  disabled={!canEdit}
                  className="input"
                  placeholder="Enter meeting name"
                />
              </div>

              <div style={{ display: 'grid', gap: 12, gridTemplateColumns: '1fr 1fr' }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Division</label>
                  <select
                    value={form.division_id}
                    onChange={(e) => handleChange('division_id', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                  >
                    <option value="">Select division</option>
                    {divisions.map((division) => (
                      <option key={division.id} value={division.id}>{division.division_name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Meeting Type</label>
                  <select
                    value={form.meeting_type_id}
                    onChange={(e) => handleChange('meeting_type_id', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                  >
                    <option value="">Select meeting type</option>
                    {meetingTypes.map((type) => (
                      <option key={type.id} value={type.id}>{type.meeting_type_name}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div style={{ display: 'grid', gap: 12, gridTemplateColumns: '1fr 1fr' }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>City</label>
                  <select
                    value={form.city_id}
                    onChange={(e) => handleChange('city_id', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                  >
                    <option value="">Select city</option>
                    {cities.map((city) => (
                      <option key={city.id} value={city.id}>{city.city_name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Zone</label>
                  <input
                    value={form.zone}
                    onChange={(e) => handleChange('zone', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                    placeholder="Enter zone or area"
                  />
                </div>
              </div>

              <div style={{ display: 'grid', gap: 12, gridTemplateColumns: '1fr 1fr' }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Start Date</label>
                  <input
                    type="date"
                    value={form.start_date}
                    onChange={(e) => handleChange('start_date', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>End Date</label>
                  <input
                    type="date"
                    value={form.end_date}
                    onChange={(e) => handleChange('end_date', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                  />
                </div>
              </div>

              {/* Participant Mix Section - Step 4 New Architecture */}
              <div style={{
                background: 'var(--background)',
                borderRadius: 'var(--radius-lg)',
                padding: 'var(--space-4)',
                border: '2px solid var(--border)',
              }}>
                <h3 style={{ fontSize: 'var(--font-lg)', fontWeight: 700, marginBottom: 'var(--space-4)' }}>
                  Attendance Planning
                </h3>
                
                <ParticipantMixGrid 
                  value={participantMix}
                  onChange={handleParticipantMixChange}
                  disabled={!canEdit}
                />

                {/* Guaranteed Pax */}
                <div style={{ marginTop: 'var(--space-4)' }}>
                  <label style={{ display: 'block', fontWeight: 600, marginBottom: 'var(--space-2)' }}>
                    Guaranteed Pax
                  </label>
                  <p style={{ fontSize: 'var(--font-xs)', color: 'var(--text-muted)', marginBottom: 'var(--space-2)' }}>
                    Commercial commitment for billing purposes. Must not exceed Total Planned Pax ({totalPlannedPax}).
                  </p>
                  <input
                    type="number"
                    min={0}
                    max={totalPlannedPax}
                    value={form.guaranteed_pax}
                    onChange={(e) => handleChange('guaranteed_pax', Number(e.target.value))}
                    disabled={!canEdit}
                    className="input"
                    placeholder="Enter guaranteed participant count"
                    style={{ maxWidth: '300px' }}
                  />
                  {guaranteedPaxError && (
                    <div style={{
                      marginTop: 'var(--space-2)',
                      padding: 'var(--space-2)',
                      background: '#fef2f2',
                      border: '1px solid #fca5a5',
                      borderRadius: 'var(--radius-sm)',
                      color: '#dc2626',
                      fontSize: 'var(--font-sm)',
                    }}>
                      ⚠ {guaranteedPaxError}
                    </div>
                  )}
                </div>
              </div>

              <div style={{ display: 'grid', gap: 12, gridTemplateColumns: '1fr 1fr' }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Accommodation Requirement</label>
                  <select
                    value={form.residential_flag ? 'yes' : 'no'}
                    onChange={(e) => handleChange('residential_flag', e.target.value === 'yes')}
                    disabled={!canEdit}
                    className="input"
                  >
                    <option value="no">No</option>
                    <option value="yes">Yes</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Hall Requirement</label>
                  <input
                    type="number"
                    min={0}
                    value={form.halls_required}
                    onChange={(e) => handleChange('halls_required', Number(e.target.value))}
                    disabled={!canEdit}
                    className="input"
                    placeholder="Number of halls"
                  />
                </div>
              </div>

              <div style={{ display: 'grid', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Seating Style</label>
                  <input
                    value={form.seating_style}
                    onChange={(e) => handleChange('seating_style', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                    placeholder="e.g. Theatre, Classroom"
                  />
                </div>
              </div>

              <div style={{ display: 'grid', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>AV Requirements</label>
                  <textarea
                    value={form.av_requirements}
                    onChange={(e) => handleChange('av_requirements', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                    rows={3}
                    placeholder="Describe audio / visual needs"
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Food Requirements</label>
                  <textarea
                    value={form.food_requirements}
                    onChange={(e) => handleChange('food_requirements', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                    rows={3}
                    placeholder="Describe catering needs"
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontWeight: 600 }}>Transport Requirements</label>
                  <textarea
                    value={form.transfer_requirements}
                    onChange={(e) => handleChange('transfer_requirements', e.target.value)}
                    disabled={!canEdit}
                    className="input"
                    rows={3}
                    placeholder="Describe transport support needed"
                  />
                </div>
              </div>

              {error && (
                <div style={{ color: 'var(--status-danger)', fontWeight: 600 }}>{error}</div>
              )}

              {/* Explore Matching Venues - Request-Driven Discovery */}
              {request && (
                <div style={{ 
                  marginTop: 'var(--space-4)', 
                  padding: 'var(--space-4)', 
                  background: 'var(--background)',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border)',
                }}>
                  <h4 style={{ fontSize: 'var(--font-md)', fontWeight: 700, marginBottom: 'var(--space-2)', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
                    <Search size={18} style={{ color: 'var(--primary)' }} />
                    Venue Discovery
                  </h4>
                  
                  {(() => {
                    // Check mandatory fields for venue exploration
                    const hasZone = !!request.zone;
                    const hasCity = !!request.city_id;
                    const hasMeetingType = !!request.meeting_type_id;
                    const hasResidentialFlag = request.residential_flag !== null && request.residential_flag !== undefined;
                    const hasPax = !!request.expected_pax;
                    
                    const canExplore = hasZone && hasCity && hasMeetingType && hasResidentialFlag && hasPax;
                    
                    if (!canExplore) {
                      const missingFields = [];
                      if (!hasZone) missingFields.push('Zone');
                      if (!hasCity) missingFields.push('City');
                      if (!hasMeetingType) missingFields.push('Meeting Type');
                      if (!hasResidentialFlag) missingFields.push('Residential/Non-Residential');
                      if (!hasPax) missingFields.push('Expected Pax');
                      
                      return (
                        <>
                          <p style={{ fontSize: 'var(--font-sm)', color: 'var(--text-muted)', marginBottom: 'var(--space-3)' }}>
                            Complete the required fields to search for matching venues.
                          </p>
                          <div style={{ 
                            display: 'flex', 
                            alignItems: 'flex-start', 
                            gap: 'var(--space-2)',
                            padding: 'var(--space-3)',
                            background: '#fef2f2',
                            borderRadius: 'var(--radius-md)',
                            marginBottom: 'var(--space-3)',
                          }}>
                            <AlertCircle size={16} style={{ color: '#dc2626', flexShrink: 0, marginTop: '2px' }} />
                            <div>
                              <p style={{ fontSize: 'var(--font-xs)', fontWeight: 600, color: '#b91c1c', marginBottom: '4px' }}>
                                Missing required fields:
                              </p>
                              <p style={{ fontSize: 'var(--font-xs)', color: '#991b1b' }}>
                                {missingFields.join(', ')}
                              </p>
                            </div>
                          </div>
                          <button 
                            className="btn btn-secondary"
                            disabled
                            style={{ opacity: 0.5, cursor: 'not-allowed' }}
                          >
                            <Search size={16} />
                            Explore Matching Venues
                          </button>
                        </>
                      );
                    }
                    
                    return (
                      <>
                        <p style={{ fontSize: 'var(--font-sm)', color: 'var(--text-muted)', marginBottom: 'var(--space-3)' }}>
                          Discover venues that match your meeting requirements. Filters will be automatically applied based on your request details.
                        </p>
                        <button 
                          className="btn btn-primary"
                          onClick={() => navigate(`${ROUTES.venueExplorer}?requestId=${request.id}`)}
                          style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}
                        >
                          <Search size={16} />
                          Explore Matching Venues
                        </button>
                      </>
                    );
                  })()}
                </div>
              )}

              <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                <button className="btn btn-secondary" onClick={handleSaveDraft} disabled={!canEdit || saving}>
                  Save Draft
                </button>
                <button className="btn btn-primary" onClick={handleSubmit} disabled={!canEdit || saving}>
                  Submit Request
                </button>
              </div>
            </div>
          </Panel>
        </div>
      )}
    </div>
  );
}

export default MeetingRequestForm;
